name: Test and Build Reusable

on:
  workflow_call:
    inputs:
      push_image:
        required: true
        type: boolean
    secrets:
      DOCKER_USER:
        required: false
      DOCKER_PASS:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Tests OK"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Siempre construye con un tag local sin usuario
      - name: Build Docker image
        run: |
          docker build -t cliente-prueba:${{ github.sha }} .

      # Solo en release: login, retag y push
      - name: Login Docker Hub
        if: inputs.push_image
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Tag Docker image for push
        if: inputs.push_image
        run: |
          docker tag cliente-prueba:${{ github.sha }} ${{ secrets.DOCKER_USER }}/cliente-prueba:${{ github.sha }}

      - name: Push Docker image
        if: inputs.push_image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/cliente-prueba:${{ github.sha }}
